database:
  connection: "jdbc:mariadb://localhost/shivas"
  user: "root"
  password: ""
  flush_delay: 30 # seconds
  save_delay: 5 # minutes
  refresh_rate: 60 # seconds

data:
  path: "/Users/antoine/Workspace/Shivas/data/"
  extension: "xml"

mods:
  path: "/Users/antoine/Workspace/Shivas/mods/"

login:
  port: 6789

game:
  id: 1
  address: "127.0.0.1"
  port: 9876

client_version: "1.29.1"
motd: "Shivas 1.0-SNAPSHOT"

commands:
  enabled: true
  prefix: "!"

world:
  max_players_per_account: 5
  delete_answer_level_needed: 10
  max_spell_level: 6
  add_all_waypoints: true
  npc_buy_coefficient: 1

start:
  size: 100
  level: 200
  kamas: 1_000_000
  map_id: 7411
  cell_id: 255
  stats:
    action_points: 6
    movement_points: 3
    vitality: 101
    wisdom: 25
    strength: 101
    intelligence: 101
    chance: 101
    agility: 101

loggers:
  info:
    name: "Informations"
    color: "#009900"
  error:
    name: "Erreur"
    color: "#C10000"
  warn:
    name: "Avertissement"
    color: "#FF8000"

fights:
  workers: 2
  turn_duration:
    - { type: AGRESSION, seconds: 51 }
    - { type: DUEL, seconds: 46 }
    - { type: ~, seconds: 31 }